### ISSUE TITLE
帮 (bang1) as ADP?

### ISSUE THREAD

**Issue by Oneplus** [UniversalDependencies/UD_Chinese-CFL#2]
hi, the [guidelines](http://universaldependencies.org/zh/pos/ADP.html) indicate to tag 帮 (bang1) as ADP. However, in both the CTB and CDT, 帮 is analyzed as VERB. In UD_Chinese-CFL, it's not very consistent among different cases and it seems it tends to tag it as VERB. Please see the following cases

```
# sent_id = CFL_F_2-17/ori
# text = 不过他们帮我找预定的青年旅社。
1	不过	不过	ADV	_	_	5	advmod	_	SpaceAfter=No
2	他们	他们	PRON	_	_	5	nsubj	_	SpaceAfter=No
*3	帮	帮	ADP	_	_	4	case	_	SpaceAfter=No
4	我	我	PRON	_	_	5	obl	_	SpaceAfter=No
5	找	找	VERB	_	_	0	root	_	SpaceAfter=No
6	预定	预定	VERB	_	_	8	acl	_	SpaceAfter=No
7	的	的	PART	_	_	6	mark:rel	_	SpaceAfter=No
8	青年旅社	青年旅社	NOUN	_	_	5	obj	_	SpaceAfter=No
9	。	。	PUNCT	_	_	5	punct	_	SpaceAfter=No
```
and
```
# sent_id = CFL_J_1-7/ori
# text = 我忙跑上前去帮他盖上了井盖。
1	我	我	PRON	_	_	3	nsubj	_	SpaceAfter=No
2	忙	忙	ADJ	_	_	3	advmod	_	SpaceAfter=No
3	跑	跑	VERB	_	_	0	root	_	SpaceAfter=No
4	上前	上前	ADP	_	_	3	case:loc	_	SpaceAfter=No
5	去	去	VERB	_	_	3	compound:dir	_	SpaceAfter=No
*6	帮	帮	VERB	_	_	5	conj	_	SpaceAfter=No
*7	他	他	PRON	_	_	6	obj	_	SpaceAfter=No
*8	盖	盖	VERB	_	_	6	xcomp	_	SpaceAfter=No
9	上	上	VERB	_	_	8	compound:vv	_	SpaceAfter=No
10	了	了	AUX	_	_	8	aux	_	SpaceAfter=No
11	井盖	井盖	NOUN	_	_	8	compound:vo	_	SpaceAfter=No
12	。	。	PUNCT	_	_	3	punct	_	SpaceAfter=No
```
So could you tell me the necessity of analyzing 帮 as ADP?

BTW, it's also unconventional to attach an ADP to VERB with `case` in UD_English (like the first example). The only case I've found is http://bionlp-www.utu.fi/dep_search/query?search=ADP%20%3Ccase%20VERB&db=UD_English-v2&case_sensitive=True&hits_per_page=50. And it looks like a typo.

If it's not necessary to tag 帮 as ADP, we should revise the document.

**Comment by wongtaksum** [comment]
Thank you for pointing out the mistake.  We have made correction already.

**Comment by Oneplus** [comment]
@wongtaksum Thanks!
