### ISSUE TITLE
Is 在 (zai4) a Chinese aspect marker?

### ISSUE THREAD

**Issue by Oneplus** [UniversalDependencies/UD_Chinese-CFL#3]
Like in this case: `我 在 标 数据` (I am annotating data), 在 indicates the actions 标注 (biao1zhu4, annotate) is in progress. So I would like to know if `在` is also an aspectual marker like `了`  and `着` or it is an adverb?

**Comment by dan-zeman** [comment]
I cannot comment on how the example relates to the current Chinese guidelines but from a cross-linguistic perspective, this resembles a nominalized predication, something like

_I am in(zai) annotating of-data._

If that interpretation is correct, then a possible analysis would be to attach 在 as a `case` dependent of 标; 我 would still be an `nsubj` of 标.

**Comment by Oneplus** [comment]
@dan-zeman Thanks for your reply. In Chinese guideline, the coverb / preposition usage of 在 is mentioned. But its function of showing an action in progress is not mentioned. CTB guideline treats 在 in this kind of situation as an adverb.

It's possible to interpret `标 数据` (annotating data) as a nominal phrase but it's very weird in my perspective of a Chinese speaker.

Another Chinese word 正 (zheng4) has the similar function, 正 and 在 can also be combined to make a disyllabic word 正在 (zheng4zai) and it also has the same function.

**Comment by wongtaksum** [comment]
In my opinion, 在 marks a progressive event but it is not considered as an aspect marker since all aspect markers in Chinese are left-bound.  Possibly in future some more right-bound marker appears and they will be considered as aspect markers as well.  In contemporary Mandarin, I consider it as an adverb.

**Comment by Oneplus** [comment]
@wongtaksum Thanks!
